### ISSUE TITLE
`M0-2-1`: Consider array copies with overlapping data

### ISSUE THREAD

**Issue by lcartey** [github/codeql-coding-standards#119]
### Affected rules
 - `M0-2-1`

### Description

The query as currently written only considers overlapping as caused by unions. We should also consider whether overlapping arrays are covered by the same rule.

### Example

```cpp
#include <cstring>
int16_t a[20];
void f2(void) {
  std::memcpy(&a[0], &a[1], 10u * sizeof(a[0]));  // Non-compliant
  std::memmove(&a[0], &a[1], 10u * sizeof(a[0])); // Compliant 
  std::memcpy(&a[1], &a[0], 10u * sizeof(a[0]));  // Non-compliant
  std::memmove(&a[1], &a[0], 10u * sizeof(a[0])); // Compliant 
}
```

**Comment by knewbury01** [comment]
is this suggestion actually about checking for UB in some set of pointer handling functions?
(like how use of overlapping [objects in memcpy](https://en.cppreference.com/w/cpp/string/byte/memcpy) is UB?)

perhaps one way forward is to look for [cases in a list of functions that would have restrict qualified pointers in c](https://github.com/github/codeql-coding-standards/blob/main/c/cert/src/rules/EXP43-C/RestrictPointerReferencesOverlappingObject.md#invoking-library-functions-with-restrict-qualified-pointers)?
