### ISSUE TITLE
`A0-1-3`: Missing some function use cases

### ISSUE THREAD

**Issue by lcartey** [github/codeql-coding-standards#121]
### Affected rules
 - `A0-1-3`

### Description

Missing the following function use cases:
 * The address of a function is taken
 * The operand of an expression in an unevaluated context
 * Functions marked with ``[[maybe_unused]]``
 * Explicitly deleted functions e.g. `=delete`
 * Use of any overload of a function in an overload set constitute a use of all members of the set.  An _overload set_ is a set of functions with the same name that differ in the number, type and/or qualifiers of their parameters.

**Comment by rak3-sh** [comment]
[PR: 347](https://github.com/github/codeql-coding-standards/pull/347) is a candidate fix for this issue.

**Comment by rvermeulen** [comment]
This is addressed in https://github.com/github/codeql-coding-standards/pull/347
