### ISSUE TITLE
`A0-1-2`: Consider additional uses for return values

### ISSUE THREAD

**Issue by lcartey** [github/codeql-coding-standards#123]
### Affected rules
 - `A0-1-2`

### Description

Consider:
 * c-style casts to `void`.
 * Assignment to `std::ignore`

### Example

```cpp
std::ignore = f();
```

**Comment by rvermeulen** [comment]
The rule excludes calls to overloaded operators for all function calls that are a top-level expression (i.e. child of an `ExprStmt`). This means that our definition of `std::ignore`, matching https://en.cppreference.com/w/cpp/utility/tuple/ignore, is correctly handled by the query. 

We need more information to proceed with the triage.

**Comment by lcartey** [comment]
Fixed by https://github.com/github/codeql-coding-standards/pull/181.
