### ISSUE TITLE
Analysis report generation fails due to Python import error

### ISSUE THREAD

**Issue by lcartey** [github/codeql-coding-standards#140]
**Describe the bug**
When running the `analysis_report.py` script the following error is observed:

```
ImportError: cannot import name 'CodeQL' from partially initialized module 'codeql' (most likely due to a circular import) 
```

**Environment**
 - CodeQL Coding Standards version: 2.8.0
 - Python version: 3.9.15
 -  CodeQL CLI bundle: codeql-bundle-20220120 (CLI version: 2.7.6)

**Comment by rvermeulen** [comment]
This has been addressed in https://github.com/github/codeql-coding-standards/pull/68/

**Comment by lcartey** [comment]
#68 has now been merged, so this should be fixed in the next release.
