### ISSUE TITLE
`A5-1-1`: Expand set of logging mechanisms

### ISSUE THREAD

**Issue by lcartey** [github/codeql-coding-standards#216]
### Affected rules
 - `A5-1-1`

### Description

This query is producing false positives because we are flagging legitimate logging or print calls. We should add support for the following:

 * Use of `std::ostream` and other supported function in a variable template - see the example below.
 * Exclude results expanded from a logging macro (based on the name of the macro)

Optional extension:
 * Ensure we capture wrappers around logging functions (i.e. functions that pass arguments _only_ a logger or printf call should be consider, themselves, logger calls).

### Example
```cpp
template <typename T>
void PrintFoo(std::ostream& os, const T& bar, const char* str) noexcept {
  const Foo& foo{GetFoo(bar)};
  os << str << "blah blah" << foo << "blah blah" << bar.baz << ".";
}
```

**Comment by knewbury01** [comment]
just a note:

cannot replicate with the fairly similar example as to above:
```
template <typename T>
void test_template(std::ostream& os, const T& bar, const char* str) noexcept {
  const Class1& foo{Class1(bar)};
  os << str << "blah blah" << foo << "blah blah" << bar.baz << "."; // COMPLIANT - literal used in logging
}
```
this is Literals because Template Functions are [explicitly omitted](https://github.com/github/codeql-coding-standards/blob/main/cpp/autosar/src/rules/A5-1-1/LiteralValueUsedOutsideTypeInit.ql#L40), but other loggings are showing up, so I will assume that if there are remaining template related issues later that those can be resurfaced

**Comment by knewbury01** [comment]
hm, also not seeing an alert related to Macros... (this testcase is annotated as it stands for before the fix for streams has been applied)

```
void test_other_logging(const char *str) noexcept {
  std::ostream os;
  os << str << "logging string"; // COMPLIANT[FALSE_POSITIVE] - literal used in stream write
}

#define WRAPPER_MACRO(X) test_other_logging(X)

void test_wrapper_logging(const char *str) noexcept {
  test_other_logging("test"); // COMPLIANT[FALSE_POSITIVE] - wrapper for logging call
  WRAPPER_MACRO("test");      // COMPLIANT - wrapper for logging call (currently not seeing this reported)
}
```
