### ISSUE TITLE
`M5-0-3`: Do not flag subscript expressions

### ISSUE THREAD

**Issue by lcartey** [github/codeql-coding-standards#233]
### Affected rules
 - `M5-0-3`

### Description

The rule title is "A cvalue expression shall not be implicitly converted to a different underlying type.".

MISRA-C++:2008 says in section 6.5 _“Expressions”_, paragraph _“Postfix expressions”_:

>  postfix-expression [ expression ]
>          **The result is not a cvalue.** The underlying type of the result is the underlying type of the array element.

Subscript expressions not being a cvalue, the rule should not apply.

### Example
```cpp
uint16_t i = 0;
foo[i] = 0;
```

**Comment by knewbury01** [comment]
is this meant to be the problematic case?
```
int8_t i = 0; 
int16_t foo[0];
foo[i] = 0;
```

**Comment by lcartey** [comment]
Closing as this was a misunderstanding. The result of a subscript expression is a cvalue, not the subscript "operand".
