### ISSUE TITLE
`A7-3-1`: `HiddenInheritedNonOverridableMemberFunction` reports false positives

### ISSUE THREAD

**Issue by anthony-williams-woven** [github/codeql-coding-standards#360]
### Affected rules
 - A7-3-1/HiddenInheritedNonOverridableMemberFunction

### Description

A7-3-1 reports violations on `operator=` in derived classes. For assignment of a derived class to do anything meaningful, it *must* provide an `operator=`, and cannot rely on the base class definition. Any report of a violation on `operator=` is thus a false positive.

### Example
```cpp
class base_class {};

class derived : private base_class {
 public:
  derived& operator=(const derived&) noexcept = default;
};
```

**Comment by lcartey** [comment]
I think this is a general problem with special member functions, which should be excluded from this rule. This is because special member functions are never inherited.

**Comment by knewbury01** [comment]
this wasnt previously auto closed simply because the syntax of the linked issue in the PR was not correct, needs to use the full keyword syntax for each issue (ie closes X and closes Y not closes X and Y)
