### ISSUE TITLE
`A8-4-8`: Allow output parameters in assign operators

### ISSUE THREAD

**Issue by lcartey** [github/codeql-coding-standards#370]
### Affected rules
 - `A8-4-8`

### Description

Output parameters are required for user defined assign operators, and so should not be reported.

### Example
```cpp
constexpr byte& operator|=(byte& lhs, const byte rhs) noexcept {
  lhs = (lhs | rhs);
  return lhs;
}
```

**Comment by rvermeulen** [comment]
Cannot reproduce this case. Needs further discussion.
