### ISSUE TITLE
`A7-1-1`: Exclude compiler generated statements for range based for loops

### ISSUE THREAD

**Issue by lcartey** [github/codeql-coding-standards#372]
### Affected rules
 - `A7-1-1`
 - `A0-1-1`

### Description

Similar to:
https://github.com/github/codeql-coding-standards/issues/309

### Example
```cpp
  for (const bool value : values) {
    do_stuff(value);
  }
```

**Comment by lcartey** [comment]
As part of this work we should do a systematic analysis of the queries using QL for QL to identify queries reporting `Variable`s as their primary location where the `isCompilerGenerated` is not included as a condition on the `where` clause.

**Comment by rvermeulen** [comment]
A0-1-1 is already address by @lcartey in b8a527cacc3.
Cannot replicate the issue for A7-1-1 because the range based variables are already filtered out.
I will explicitly exclude compiler generated variables, but we unfortunately cannot add a test case for this report.
