### ISSUE TITLE
`A16-2-2`: Consider excluding redundant includes

### ISSUE THREAD

**Issue by lcartey** [github/codeql-coding-standards#453]
### Affected rules
 - `A16-2-2`
### Description

The query currently reports redundant includes - e.g. includes which provide used symbols which are provided by earlier includes. I don't believe redundant includes are intended to be flagged by this rule per the justification.

Note: this doesn't occur if a declaration is used in the directly included file. In that case we assume the redundancy is intended. However, if a library is structured so that the public header forwards to an internal header, we can get "spurious" redundancy results.

#### source.c
```cpp

#include "a.h"
#include "lib.h" // Seen as useless

void test() {
  f();
  g();
}
```
#### a.h
```cpp
#include "lib.h"

void g() {
  f();
}
```
#### lib.h
```cpp
#include "lib_internal.h"
```
#### lib_internal.h
```cpp
void f();
```

**Comment by kraiouchkine** [comment]
@lcartey I am not able to reproduce this behaviour with the test case provided. The query reports no results for a test with the four files in your example. Am I misunderstanding that we *should* report the `lib.h` include in `source.c`?

**Comment by kraiouchkine** [comment]
> @lcartey I am not able to reproduce this behaviour with the test case provided. The query reports no results for a test with the four files in your example. Am I misunderstanding that we _should_ report the `lib.h` include in `source.c`?

The issue is reproducible when "lib.h" is included after the first include ("a.h"). I've raised a PR to address this issue.
