### ISSUE TITLE
Missing attestations: @jketema

### ISSUE THREAD

**Issue by kraiouchkine** [github/codeql-coding-standards#500]
Hello @jketema,

This issue has been automatically created because there are missing attestations in the following pull requests you approved:

| Pull Request | Problems |
|--------------|----------|
| https://github.com/github/codeql-coding-standards/pull/478 | Release change checklist |
| https://github.com/github/codeql-coding-standards/pull/458 | Change request type<br>Rules with added or modified queries<br>Release change checklist |
| https://github.com/github/codeql-coding-standards/pull/419 | Rules with added or modified queries<br>Release change checklist |
| https://github.com/github/codeql-coding-standards/pull/325 | Release change checklist |
| https://github.com/github/codeql-coding-standards/pull/290 | Release change checklist |
| https://github.com/github/codeql-coding-standards/pull/270 | Release change checklist |
| https://github.com/github/codeql-coding-standards/pull/114 | Release change checklist |
| https://github.com/github/codeql-coding-standards/pull/70 | Release change checklist |
| https://github.com/github/codeql-coding-standards/pull/2 | Release change checklist |

Please review these pull requests, complete the missing attestation checkboxes, and update this issue once complete.

Thank you!

**Comment by jketema** [comment]
I've updated #2. All the other ones target the `next` branch, and I have ignored those for now per the internal discussion.
