### ISSUE TITLE
Missing attestations: @rvermeulen

### ISSUE THREAD

**Issue by kraiouchkine** [github/codeql-coding-standards#504]
Hello @rvermeulen,

This issue has been automatically created because there are missing attestations in the following pull requests you approved:

| Pull Request | Problems |
|--------------|----------|
| https://github.com/github/codeql-coding-standards/pull/411 | Release change checklist<br>Query development review checklist |
| https://github.com/github/codeql-coding-standards/pull/409 | Rules with added or modified queries<br>Release change checklist<br>Query development review checklist |
| https://github.com/github/codeql-coding-standards/pull/358 | Release change checklist<br>Query development review checklist |
| https://github.com/github/codeql-coding-standards/pull/293 | Release change checklist<br>Query development review checklist |
| https://github.com/github/codeql-coding-standards/pull/25 | Query development review checklist |
| https://github.com/github/codeql-coding-standards/pull/3 | Query development review checklist |

Please review these pull requests, complete the missing attestation checkboxes, and update this issue once complete.

Thank you!

```[tasklist]
### Tasks
- [x] 411
- [x] 409
- [x] 358
- [x] 293
- [x] 25
- [x] 3
```

**Comment by rvermeulen** [comment]
Resolved missing attestations.
