### ISSUE TITLE
`A3-9-1`:  Variables having template parameter type are recognized as having `variable-width type`.

### ISSUE THREAD

**Issue by marco-seoul-robotics** [github/codeql-coding-standards#536]
### Affected rules
 - `A3-9-1`

### Description
Variables with template parameter type are recognized as having `variable-width type`.

### Example
```cpp
template <class TScalar>
explicit constexpr Matrix(TScalar value = TScalar{}) noexcept { data_.fill(value); }
```
Error was detected here, describing `Variable 'value' has variable-width type.`

**Comment by lcartey** [comment]
Closing as a duplicate of https://github.com/github/codeql-coding-standards/issues/540.
