### ISSUE TITLE
`M5-0-3`, `M5-0-7`, `M5-0-8`, `M5-0-9`:  Casted argument of function call is wrongly considered as a `cvalue`

### ISSUE THREAD

**Issue by nbusser** [github/codeql-coding-standards#602]
### Affected rules
 - `M5-0-3`
 - `M5-0-7`
 - `M5-0-8`
 - `M5-0-9`

### Description

Return value of `static_cast` seems to be treated as a `cvalue` interferring with several MISRA rules:

#### M-0-8

When upcasting variable using `static_cast` and rightaway using the result in another expression, it triggers a M5-0-9 warning (illustrated in example function `false_positive`).

It forces the user to create a intermediate variable containing the result of the `static_cast`, then using this intermediate variable in the expression (illustrated in example function `true_negative`).

#### M-0-9

When changing variable's signedness using `static_cast` and rightaway using the result in another expression, it triggers a M5-0-9 warning (illustrated in example function `false_positive`).

It forces the user to create a intermediate variable containing the result of the `static_cast`, then using this intermediate variable in the expression (illustrated in example function `true_negative`).

#### M-0-8
```cpp
void false_positive() { 
    std::vector<std::uint8_t> v{0};

    std::uint32_t u32{0};
    v.at(static_cast<std::size_t>(u32)); // Triggers a M5-0-8 warning
}

void true_negative() {
    std::vector<std::uint8_t> v{0};

    std::size_t st = static_cast<std::size_t>(u32);
    v.at(st); // Does not trigger a M5-0-8 warning
}
```

#### M-0-9

```cpp
void false_positive() { 
  std::vector<std::uint8_t> v{0};

  std::int32_t s32{0};
  v.at(static_cast<std::size_t>(s32)); // Triggers a M5-0-9 warning
}

void true_negative() {
  std::vector<std::uint8_t> v{0};

  std::size_t st = static_cast<std::size_t>(s32);
  v.at(st); // Does not trigger a M5-0-9 warning
}
```

**Comment by lcartey** [comment]
Thanks! This happens because function argument expressions are considered _cvalues_ in MISRA, and we (incorrectly, in this case) consider the `s32` to be an function argument in `v.at(static_cast<std::size_t>(s32))`. This is because conversions, such as casts, are represented separately in our model.

**Comment by lcartey** [comment]
This also affects a few other `M5-0-*` rules. It also affects return values.

Fix has been created here:
https://github.com/github/codeql-coding-standards/pull/778

**Comment by nbusser-sr** [comment]
Thank you, I was about to report other affected `M5-0-*` rules
