### ISSUE TITLE
`M9-3-3`:  Ignore uninstantiated templates

### ISSUE THREAD

**Issue by lcartey** [github/codeql-coding-standards#616]
### Affected rules
 - `M9-3-3`
### Description

Query reports cases in uninstantiated templates.

**Comment by WINNING999** [comment]
Use unsubstantiated templates instead.

**Comment by WINNING999** [comment]
> ### Affected rules
>  - `M9-3-3`
> ### Description
> 
> Query reports cases in uninstantiated templates.
> 
> 

Unsubstantiated templates
