### ISSUE TITLE
How can I use codeql-coding-standards to analyze my cpp-ql database

### ISSUE THREAD

**Issue by ysuLihua** [github/codeql-coding-standards#669]
When i run analyze command, I meet this problem:

![image](https://github.com/user-attachments/assets/5bc2e2c6-d8d0-4848-a0fd-78f1edfa4514)

How can i resolve is? Thanks!

**Comment by lcartey** [comment]
Hi @ysuLihua. If you are running the queries from a checkout of the repository, you first need to run the command listed in the screenshot - `codeql pack install` - to download the required dependencies. Alternatively you can download the release, which already includes the dependencies.
