### ISSUE TITLE
Links to github/coding-standards-help

### ISSUE THREAD

**Issue by iglesias** [github/codeql-coding-standards#675]
Hi, it is a minor doc issue, not directly related to queries, false positives/negatives, or security vulnerabilities. I try opening a blank issue.

The links to https://github.com/github/codeql-coding-standards-help in the development handbook lead to 404. There are also a couple more references to it in a workflow file and in a generate_rules script.

**Comment by lcartey** [comment]
Thanks for the report. I'm afraid the `github/codeql-coding-standards-help` repository is not open source. This is because it contains contents from third party coding standards where we do not have the intellectual property rights to open source it, hence the separate repository.
