### ISSUE TITLE
`IdentifierHiddenSharedQuery` broken on the `next` branch

### ISSUE THREAD

**Issue by jketema** [github/codeql-coding-standards#749]
We've made some improvements to `getParentScope` in the C/C++ QL library: https://github.com/github/codeql/pull/17776

This has broken `IdentifierHiddenSharedQuery` on `next`: https://github.com/github/codeql-coding-standards/commit/2778d662e2cf701b351b2466916e9e0f03dd31f8. It's not fully clear to me what the query is supposed to achieve and how to fix it. Hence, I've just updated the expected test results.

**Comment by lcartey** [comment]
@jketema I believe this should be addressed (incidentally) by https://github.com/github/codeql-coding-standards/pull/813, which implements the desired behaviour for that query in preference to the default `getParentScope` behaviour.
