### ISSUE TITLE
`EXP52-CPP`:  exclude `decltype`s which are structurally equivalent to expressions for which they represent the type

### ISSUE THREAD

**Issue by rvermeulen** [github/codeql-coding-standards#91]
### Affected rules
 - cpp/cert/do-not-rely-on-side-effects-in-decl-type-operand

### Description

The rule looks at expression passed to `decltype` that exhibit side effects.
The goal of this is to detect cases where a programmer relies on side effects that do not occur because the `decltype` operand is not evaluated.

However, this cannot be the case for `dectype` usage in function or method signatures, but we still report these.

### Example
```cpp
auto foo(...) -> decltype(<expr with side effects>)
}
```

### Proposed solution

Exclude `decltype` part of a function/method declaration.

**Comment by lcartey** [comment]
Closing as this change is effectively encapsulated in https://github.com/github/codeql-coding-standards/issues/369.
